dataset_params:
  im_path: '/Users/neeravkaushal/Codes/diffusion/data/mnist/train'
  num_train_samples: 20000

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels : 2
  im_size : 64
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 1
  num_mid_layers : 1
  num_up_layers : 1
  num_heads : 4
  num_groups : 2

train_params:
  task_name: 'v1'
  batch_size: 8 #64
  num_epochs: 5 #40
  num_samples : 100
  num_grid_rows : 10
  lr: 0.0001
  ckpt_name: 'ddpm_ckpt.pth'